version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - database
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword